- name: "Install NFS client packages for Ubuntu"
  ansible.builtin.include_tasks: ubuntu/main.yml
  when: ansible_os_family == "Ubuntu"

- name: "Install NFS client packages for Arch Linux"
  ansible.builtin.include_tasks: archlinux/main.yml
  when: ansible_os_family == "Archlinux"

