- name: "Restart all NFS services, as required"
  ansible.builtin.service:
    name: "{{ setting.nm }}"
    state: "{{ 'restarted' if setting.st else 'stopped' }}"
  loop:
    - { nm: "{{ nfs_client_service_name }}",
        st: "{{ en_v3 or en_v4 }}" }
    - { nm: "{{ nfs_client_mapping_service_name }}",
        st: "{{ en_v4 and en_v4_map_svc }}" }
    - { nm: "{{ nfs_client_delegation_service_name }}",
        st: "{{ en_v4 and en_v4_cli_del }}" }
  become: true
  become_user: root
  listen: restart_nfs_client_services

