- name: "Create main/parent NFS share mount dir at '{{ nfs_client_nfs_shares_main_mount_dir_path }}'"
  ansible.builtin.file:
    path: "{{ nfs_main_mnt_dir }}"
    state: directory
    owner: "root"
    group: "{{ nfs_client_nfs_share_dirs_root_group }}"
    mode: "755"
  become: true
  become_user: root

- name: "Create each NFS share mount subdir"
  ansible.builtin.file:
    path: "{{ nfs_main_mnt_dir }}/{{ sh.share }}"
    state: directory
    owner: "root"
    group: "{{ nfs_client_nfs_share_dirs_root_group }}"
    mode: "755"
  loop: "{{ nfs_client_nfs_shares_to_mount }}"
  loop_control:
    loop_var: sh
  become: true
  become_user: root

